spring:
  application:
    name: sms-service
  pid:
    file: app.pid

  main:
    web-application-type: reactive
  data:
    redis:
      host: redis-11323.fcrce180.us-east-1-1.ec2.redns.redis-cloud.com
      port: 11323
      user: default
      password: gWm2yw24rlENpYxr43y5acJgxFzWTQ2Y
      database: 0

server:
  port: ${SP_PORT:8080}


# user-defined configuration 
custom:
  internal-ip: ${POD_IP:127.0.0.1}:${SP_PORT:8080}
    