spring:
  application:
    name: sms-service
  lifecycle:
    timeout-per-shutdown-phase: 30s
  pid:
    file: app.pid

  main:
    web-application-type: reactive



server:
  port: 8080
  shutdown: graceful


    