apiVersion: apps/v1
kind: Deployment
metadata:
  name: sms-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: v1
    spec:
      containers:
      - image: sahtanimohcine/sms
        name: sms-service
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
