name: dockerize

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3
    
    # Log in to Docker Hub or GHCR (if pushing to a registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sms:latest .
      
    # Push the Docker image to a registry (optional)
    - name: Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sms:latest .