name: dockerize

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21' 
        distribution: 'oracle'


    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository  
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} 
        restore-keys: |
          ${{ runner.os }}-maven-


    - name: Build with Maven
      run: mvn clean package -DskipTests
    
    # Log in to Docker Hub or GHCR (if pushing to a registry)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sms:latest .
      
    # Push the Docker image to a registry (optional)
    - name: Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/sms:latest .
